'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronRight, LockKeyhole, Search, Send } from 'lucide-react';
import { hashPin } from '@/lib/security';
import { supabase, User, Message, Rank } from '@/lib/supabase';

const ranks: Rank[] = ['Leader','Guardian','Member','Newcomer'];
const getRank = (u?: Partial<User> | null): Rank => u?.rank && ranks.includes(u.rank) ? u.rank : 'Member';
const time = (v: string) => new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
type ChatMessage = {id:string; author:string; authorId:string; text:string; rank:Rank; time:string; own:boolean};

export function ChatWorkspace({ user, onLock, onDelete }: { user: User; onLock: () => void; onDelete: () => void }) {
 const [privateRoom,setPrivateRoom]=useState(false),[target,setTarget]=useState<User|null>(null),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[messages,setMessages]=useState<ChatMessage[]>([]),[stats,setStats]=useState({total:0,active:0,community:0}),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const map = async (rows: Message[]) => { if(!supabase) return []; const ids=[...new Set(rows.map(r=>r.sender_id).filter(Boolean))] as string[]; const {data}=await supabase.from('users').select('*').in('id',ids); const users=new Map((data??[]).map(u=>[u.id,u as User])); return rows.map(r=>{const id=r.sender_id??'unknown', sender=users.get(id); return {id:`${r.receiver_id?'private':'community'}-${r.id}`,author:sender?.nickname??`identity-${id.slice(0,5)}`,authorId:id,text:r.content??'',rank:getRank(sender??(id===user.id?user:null)),time:time(r.created_at),own:id===user.id};}); };
 const load = async()=>{if(!supabase)return; setLoading(true); let q=supabase.from('messages').select('*').order('created_at',{ascending:true}).limit(100); if(!privateRoom)q=q.is('receiver_id',null); else if(target)q=q.or(`and(sender_id.eq.${user.id},receiver_id.eq.${target.id}),and(sender_id.eq.${target.id},receiver_id.eq.${user.id})`); else {setLoading(false);return;} const {data}=await q;if(data)setMessages(await map(data as Message[]));setLoading(false);};
 const loadStats=async()=>{if(!supabase)return;const [{count:total},{count:active},{data:rows}]=await Promise.all([supabase.from('users').select('id',{count:'exact',head:true}),supabase.from('users').select('id',{count:'exact',head:true}).eq('is_online',true),supabase.from('messages').select('sender_id').is('receiver_id',null)]);setStats({total:total??0,active:active??0,community:new Set((rows??[]).map(r=>r.sender_id).filter(Boolean)).size});};
 useEffect(()=>{loadStats();load();if(!supabase)return;supabase.from('users').update({is_online:true,last_seen:new Date().toISOString()}).eq('id',user.id);const c=supabase.channel(`room-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>{load();loadStats();}).subscribe();return()=>{supabase.removeChannel(c);supabase.from('users').update({is_online:false,last_seen:new Date().toISOString()}).eq('id',user.id);};},[privateRoom,target?.id]);
 const openPrivate=async()=>{if(!supabase)return;const pin=query.replace(/\D/g,'').slice(0,4);if(pin.length!==4)return setError('Enter a 4-digit Chat PIN.');const {data}=await supabase.from('users').select('*').eq('connection_pin',await hashPin(pin)).neq('id',user.id).maybeSingle();if(!data)return setError('No private channel found for that PIN.');setTarget(data as User);setPrivateRoom(true);setQuery('');setError('');};
 const send=async()=>{const text=draft.trim();if(!text||!supabase||(privateRoom&&!target))return;const {error:e}=await supabase.from('messages').insert({sender:'he',sender_id:user.id,receiver_id:privateRoom?target?.id:null,content:text,message_type:'text'});if(!e)setDraft('');};
 const deleteIdentity=async()=>{if(!supabase||!window.confirm('Delete this anonymous identity and its messages forever?'))return;await supabase.from('messages').delete().or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`);const {error:e}=await supabase.from('users').delete().eq('id',user.id);if(!e)onDelete();};
 const visible=useMemo(()=>messages.filter(m=>privateRoom?m.id.startsWith('private-'):m.id.startsWith('community-')),[messages,privateRoom]);
 return <div className="workspace"><header className="mobile-top"><span>VEILROOM</span><button onClick={onLock}>Lock</button></header><main className="workspace-main"><div className="topbar"><div><span className="eyebrow">ANONYMOUS NETWORK / 2026</span><h1>Private by design.</h1></div><span className="privacy"><LockKeyhole size={14}/> DATA-ONLY DASHBOARD</span></div><StatsCardsInline stats={stats}/><section className="gateway"><div className="gateway-icon"><Search/></div><div><span className="eyebrow">HIDDEN SEARCH GATEWAY</span><h2>Open a private channel</h2><p>Enter a trusted person’s 4-digit Chat PIN. Nothing is suggested, indexed, or listed.</p></div><div className="searchbox"><input value={query} onChange={e=>{setQuery(e.target.value.replace(/\D/g,'').slice(0,4));setError('')}} onKeyDown={e=>e.key==='Enter'&&openPrivate()} placeholder="Chat PIN · · · ·" inputMode="numeric" maxLength={4}/><button onClick={openPrivate}><ChevronRight/></button></div>{error&&<small className="error">{error}</small>}</section><section className="room"><div className="room-head"><div><span className="eyebrow">● LIVE ROOM</span><h2>{privateRoom&&target?`Private channel · ${target.nickname}`:'Community room'}</h2><p>{privateRoom?'PIN-gated direct messaging. No contact list exists.':'A shared room for registered identities. Nicknames only.'}</p></div><span className="room-lock"><LockKeyhole size={14}/> {privateRoom?'PIN-gated':'open to members'}</span></div><div className="messages">{loading?<div className="empty">Loading secure room…</div>:visible.length===0?<div className="empty">This channel is empty.<small>Send the first message when you’re ready.</small></div>:visible.map(m=><article className={`message ${m.own?'own':''}`} key={m.id}><div className="avatar">{m.author[0]?.toUpperCase()}</div><div><div className="meta"><b>{m.author}</b><span>{m.rank}</span><time>{m.time}</time></div><p>{m.text}</p></div></article>)}</div><div className="composer"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={privateRoom?'Write privately…':'Write to the community…'}/><button onClick={send}><Send size={17}/></button></div></section><div className="mobile-actions"><button onClick={onLock}>Lock session</button><button onClick={deleteIdentity}>Delete identity</button></div></main></div>;
}
function StatsCardsInline({stats}:{stats:{total:number;active:number;community:number}}){return <section className="stats-grid"><div><span>TOTAL MEMBERS</span><strong>{stats.total}</strong><small>registered identities</small></div><div><span>TOTAL ACTIVE MEMBERS</span><strong>{stats.active}</strong><small>online right now</small></div><div><span>ACTIVE IN COMMUNITY</span><strong>{stats.community}</strong><small>posting identities</small></div></section>}
